### ISSUE TITLE
Add a link to my SQL implementation

### ISSUE THREAD

**Issue by Winterleaf** [WebDAVSharp/WebDAVSharp.Server#16]
Ewout,

Could you be kind enough to add a link to my SQL Server implementation?  Also update the credits and add me to it on the ReadMe?
https://github.com/Winterleaf/Winterleaf-WebDavSharp.SQLExample

**Comment by EMerckx** [comment]
Sure, I'd be glad to update it, and thank you for contributing. 
The ReadMe has been updated by now, so I'll close this issue. If the ReadMe doesn't satisfy you, feel free to reopen the issue.
