### ISSUE TITLE
Several issues: no identity, public default handlers, updating NuGET restore packages

### ISSUE THREAD

**Issue by AlexAtNet** [WebDAVSharp/WebDAVSharp.Server#6]
Hello,

I'm evaluating the WebDAV for the project and have a few code changes that I would like to discuss or pull into the master. Specifically:

1) I would like the server to handle some URLs without authentication (with default identity) - this leads to NullPointerException on the line https://github.com/WebDAVSharp/WebDAVSharp.Server/blob/master/WebDAVServer.cs#L245.
2) There is a typo in https://github.com/WebDAVSharp/WebDAVSharp.Server/blob/master/WebDAVExtensions.cs#L72 - it compares url with uri.
3) I would like to use prefix "http://*:PORT/". Even if type 2) is fixed, it will not construct a proper handler.
4) NuGET can be migrated - http://docs.nuget.org/Consume/Package-Restore/Migrating-to-Automatic-Package-Restore

If you agree with the changes, I would be happy to make a pull request. Should I just create it for master or for some another branch?

Thanks.

**Comment by EMerckx** [comment]
Hello

I certainly agree with options 2 and 4.
But I have a question about option 1, which URLs would you like to reach with a default identity?
And about option 3, do you mean that PORT should be a variable?

The branch called development is being used for development purposes. If you could make a pull request to that branch, that would be great.
https://github.com/WebDAVSharp/WebDAVSharp.Server/tree/development

Thank you for having interest in the project.
Sincerely yours,
Ewout.

**Comment by AlexAtNet** [comment]
1. I'm merging WebDAV server with existing service with own HTTP-derived protocol and some of its URLs should be publicly accessible. Currently I've implemented it by adding custom HTTP method handlers to WebDAV instance but it requires some workarounds like moving authentication and making buildin WebDAV handlers public. Something like that:

    let handlers = [ [ _wdMethodHandlers ]; [ for item in WebDavMethodHandlers.BuiltIn do yield item ] ] |> List.toSeq |> List.concat
    wdServer <- Some(new WebDavServer(new WebDavDiskStore(@"c:\Projects\WebDAVStorage"), _listener, handlers))

This work is ongoing so no rush - I will come up with something to discuss later.

2. Ok, will do.

3. No, it is `*` what cause troubles now - the `GetPrefixUri` looks for the prefix by comparing the URL with prefix but in case the prefix is `http://*:81/` (for example) and the URL is `http://localhost:81/` then this approach will not work. Currently I've fixed it by substituting `*` with the URL's host.

4. Ok. Will do. 

> Thank you for having interest in the project.

You are welcome :) It looks like it is the best WebDAV implementation in the NuGET so far.

**Comment by AlexAtNet** [comment]
2, 3, 4 - pull requests: https://github.com/WebDAVSharp/WebDAVSharp.Server/pull/8 and https://github.com/WebDAVSharp/WebDAVSharp.Server/pull/7

1\. I've solved it by returning context in the HttpListener wrapper:

    let _listener = {
        new IHttpListener with

            member x.GetContext abortEvent =
                let ctx = _getHttpListenerContext(abortEvent)
                match ctx with

and `_getHttpListenerContext` is

    let rec _getHttpListenerContext abortEvent =
        let ar = _httpListener.BeginGetContext(null, null)
        let index = WaitHandle.WaitAny([| abortEvent; ar.AsyncWaitHandle |]);
        if index = 0 then
            None
        else
            let context = _httpListener.EndGetContext(ar)
            let request = context.Request

            sprintf "Request: %s %s" request.HttpMethod request.Url.AbsolutePath |> _peerLog

            let someContext = match request.HttpMethod with
                              | "xxx" -> HandleRequest context; None
                              | ...
                              | _ -> Some(context)
            match someContext with
            | Some(_) -> someContext
            | _ -> _getHttpListenerContext(abortEvent)

in this way the request is first processed by my router and then passed to the server. So no changes are necessary.

**Comment by AlexAtNet** [comment]
Feel free to reopen if you have questions
